/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apcs.webscrap;

import java.awt.event.KeyEvent;
import java.time.LocalTime;
//import static apcs.webscrap.TenMonkeyTypes.getWPM;
import java.util.Scanner;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;

/**
 *
 * @author teevint.prak
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        linkBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rankBox = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        wordsDisplay = new javax.swing.JTextArea();
        typingArea = new javax.swing.JTextField();
        timeBox = new javax.swing.JTextField();
        wrongWordsBox = new javax.swing.JTextField();
        wpmBox = new javax.swing.JTextField();
        totalWordsBox = new javax.swing.JTextField();
        correctWordsBox = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("10 Monkey Types");
        setForeground(java.awt.Color.black);
        setMaximumSize(new java.awt.Dimension(1174, 658));
        setMinimumSize(new java.awt.Dimension(1174, 658));
        setSize(new java.awt.Dimension(1174, 658));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(1174, 658));
        jPanel1.setMinimumSize(new java.awt.Dimension(1174, 658));
        jPanel1.setPreferredSize(new java.awt.Dimension(1174, 658));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 117, 58));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("10 Monkey Types");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, 46));

        linkBox.setBackground(new java.awt.Color(51, 51, 51));
        linkBox.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        linkBox.setForeground(new java.awt.Color(255, 117, 58));
        linkBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linkBox.setText("Link");
        linkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkBoxActionPerformed(evt);
            }
        });
        linkBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                linkBoxKeyPressed(evt);
            }
        });
        jPanel1.add(linkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 650, 40));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 117, 58));
        jLabel2.setText("Wrong Words:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 160, 30));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 117, 58));
        jLabel3.setText("Created using NetBeans");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 180, 30));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 117, 58));
        jLabel4.setText("Correct Words:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 170, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 117, 58));
        jLabel5.setText("WPM:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 90, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 117, 58));
        jLabel6.setText("Time: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 90, 30));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 117, 58));
        jLabel8.setText("Rank:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 90, 30));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 117, 58));
        jLabel9.setText("Version 1.0");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 580, 180, 30));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 117, 58));
        jLabel10.setText("Developed by: Teevint Prak");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 180, 30));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 117, 58));
        jLabel11.setText("https://github.com/TeevintPrak");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, 180, 30));

        rankBox.setEditable(false);
        rankBox.setBackground(new java.awt.Color(51, 51, 51));
        rankBox.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        rankBox.setForeground(new java.awt.Color(255, 117, 58));
        rankBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rankBox.setToolTipText("");
        rankBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankBoxActionPerformed(evt);
            }
        });
        jPanel1.add(rankBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 170, 40));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 117, 58));
        jLabel12.setText("Words:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 90, 30));

        wordsDisplay.setEditable(false);
        wordsDisplay.setBackground(new java.awt.Color(51, 51, 51));
        wordsDisplay.setColumns(20);
        wordsDisplay.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        wordsDisplay.setForeground(new java.awt.Color(204, 102, 0));
        wordsDisplay.setLineWrap(true);
        wordsDisplay.setRows(5);
        jScrollPane2.setViewportView(wordsDisplay);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 650, 260));

        typingArea.setBackground(new java.awt.Color(51, 51, 51));
        typingArea.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        typingArea.setForeground(new java.awt.Color(255, 117, 58));
        typingArea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        typingArea.setText("Type Here");
        typingArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typingAreaActionPerformed(evt);
            }
        });
        typingArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                typingAreaKeyPressed(evt);
            }
        });
        jPanel1.add(typingArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 650, 70));

        timeBox.setEditable(false);
        timeBox.setBackground(new java.awt.Color(51, 51, 51));
        timeBox.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        timeBox.setForeground(new java.awt.Color(255, 117, 58));
        timeBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        timeBox.setToolTipText("");
        timeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeBoxActionPerformed(evt);
            }
        });
        jPanel1.add(timeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 170, 40));

        wrongWordsBox.setEditable(false);
        wrongWordsBox.setBackground(new java.awt.Color(51, 51, 51));
        wrongWordsBox.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        wrongWordsBox.setForeground(new java.awt.Color(255, 117, 58));
        wrongWordsBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wrongWordsBox.setToolTipText("");
        wrongWordsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrongWordsBoxActionPerformed(evt);
            }
        });
        jPanel1.add(wrongWordsBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, 170, 40));

        wpmBox.setEditable(false);
        wpmBox.setBackground(new java.awt.Color(51, 51, 51));
        wpmBox.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        wpmBox.setForeground(new java.awt.Color(255, 117, 58));
        wpmBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        wpmBox.setToolTipText("");
        wpmBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wpmBoxActionPerformed(evt);
            }
        });
        jPanel1.add(wpmBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 170, 40));

        totalWordsBox.setEditable(false);
        totalWordsBox.setBackground(new java.awt.Color(51, 51, 51));
        totalWordsBox.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        totalWordsBox.setForeground(new java.awt.Color(255, 117, 58));
        totalWordsBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalWordsBox.setToolTipText("");
        totalWordsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalWordsBoxActionPerformed(evt);
            }
        });
        jPanel1.add(totalWordsBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 170, 40));

        correctWordsBox.setEditable(false);
        correctWordsBox.setBackground(new java.awt.Color(51, 51, 51));
        correctWordsBox.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        correctWordsBox.setForeground(new java.awt.Color(255, 117, 58));
        correctWordsBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        correctWordsBox.setToolTipText("");
        correctWordsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctWordsBoxActionPerformed(evt);
            }
        });
        jPanel1.add(correctWordsBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, 170, 40));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 117, 58));
        jLabel13.setText("Code available on GitHub:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 610, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1174, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_linkBoxActionPerformed

    private void rankBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rankBoxActionPerformed

    private void typingAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typingAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typingAreaActionPerformed

    private void timeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeBoxActionPerformed

    private void wrongWordsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrongWordsBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wrongWordsBoxActionPerformed

    private void wpmBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wpmBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wpmBoxActionPerformed

    private void totalWordsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalWordsBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalWordsBoxActionPerformed

    private void correctWordsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctWordsBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctWordsBoxActionPerformed

    private void linkBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linkBoxKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) //Checks if enter key is pressed
        {
            String text = linkBox.getText().trim(); 
            String urlHTTP = "https://10fastfingers.com/"; //For everything to work, the link must be from 10fastfingers
            if(!(text.equals(" ") || text.equals("")) && (text.contains(urlHTTP))) 
            {
                resetAllValues(); //Resets all value to prepare for a new session
                wordsDisplay.setText(""); //Clears the text so a new one can be place
                backEnd.setUp(text); //This will call the setUp to scrape and and organize the text into an ArrayList
                String testingWords = backEnd.printWords(); //Prints the arrayList into String
                wordsDisplay.append(testingWords); //appends it the String to text Area.
            }
        }
        
    }//GEN-LAST:event_linkBoxKeyPressed
   
   private void resetAllValues()  //Resets all value to prepare for a new session
   {    
        backEnd.resetWordBank();
        typedWords.clear();
        startTime = 0;
        timer = false;  //Restarts the timer
        typedFirstWord = false; //Resets first word because it is not typed
   }
    
   //Starts the timer to use for calculations
   private void startTimer()
   {
       
       if(timer) //Start timer only when timer == true so that it doesn't run forever
       {
            startTime = 0;
            startTime = LocalTime.now().toNanoOfDay();
            System.out.println(Double.toString(startTime) + " is start time");
       }
       else if(!timer) //End timer only when timer == false so that we can tell to stop
        {
            System.out.println("End timer.");
            double end = LocalTime.now().toNanoOfDay();
            System.out.println("End time = " + end);
            double elaspedTimeInSeconds = (end - startTime)/1000000000.0; //calculate the elasped time by subtracting and dividing by 1 million to convert nano to sec.
            System.out.println("elaspedTimeInSeconds");
            end = 0;
            showResults(elaspedTimeInSeconds);
            
        }
   }
   
    //Display the results in their specific box
   private void showResults(double elaspedTimeInSeconds) //Display the results in their specific box
   {
       int[] results = backEnd.evaluate(typedWords, elaspedTimeInSeconds); //Gets all the calculation as arrays because of all the multiple values
       int wpm = results[0];
       int totalWords = results[1];
       int correctWords = results[2];
       int wrongWords = results[3];
       int time = results[4];
       String rank = backEnd.getRank(wpm, wrongWords); //Measures rank of the typer based on their WPM
       
       wpmBox.setText(Integer.toString(wpm));
       totalWordsBox.setText(Integer.toString(totalWords));
       correctWordsBox.setText(Integer.toString(correctWords));
       wrongWordsBox.setText(Integer.toString(wrongWords));
       rankBox.setText(rank);
       timeBox.setText(Integer.toString(time));
       
   }
   
   
    
    private void typingAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_typingAreaKeyPressed
        // TODO add your handling code here:
        int wordCount = 0;    
        wordCount = backEnd.getWordCount(); 
        
        //Check if the typer has typed clicked space and hasnt typed the first word
        if(evt.getKeyCode() == KeyEvent.VK_SPACE && !typedFirstWord) 
        {
            timer = true;
            startTimer(); //Starts the timer for when the first word is recorded
            System.out.println("Start timer"); 
            typedFirstWord = true;
        }
        
        //Checks for the a space and input the word into an ArrayList
        if(evt.getKeyCode() == KeyEvent.VK_SPACE) 
        {
            String typedWord = typingArea.getText().trim();
            if(typedWords.size() == wordCount-1) //If the amount of words typed is one less then the text than record the last word and stop timer to prevent outOfBounds
            {
                timer = false;
                startTimer();
            }
            else if(!(typingArea.getText().equals("")&&typingArea.getText().equals(" "))) //Only records when ever there is a letter or word typed
            {
                typedWords.add(typedWord);
            }
            
            typingArea.setText(""); //Clears the typing area for new word
        }
        
        //If typer clicks enter means they are done 
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
            timer = false;
            startTimer();
        }
        
    }//GEN-LAST:event_typingAreaKeyPressed

    /**
     * @param args the command line arguments
     */
    
    //Class variables, used by many functions 
    private ArrayList<String> typedWords = new ArrayList<String>();
    private boolean typedFirstWord = false;
    private boolean timer = false;
    private TenMonkeyTypes backEnd = new TenMonkeyTypes();
    double startTime = 0;
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField correctWordsBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField linkBox;
    private javax.swing.JTextField rankBox;
    private javax.swing.JTextField timeBox;
    private javax.swing.JTextField totalWordsBox;
    private javax.swing.JTextField typingArea;
    private javax.swing.JTextArea wordsDisplay;
    private javax.swing.JTextField wpmBox;
    private javax.swing.JTextField wrongWordsBox;
    // End of variables declaration//GEN-END:variables
}
